about/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.about, name='home'),
]

contact/urls.py
#contact/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.contact, name='contact'),
    ]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('about.urls')),
    path('contact/', include('contact.urls')),
    path('polls/', include('polls.urls')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path
from . import views

app_name = "polls"
urlpatterns = [ path("", views.index, name="index"),
                path("<int:question_id>/", views.detail, name="detail"),
                path("<int:question_id>/results/", views.results, name="results"),
                path("<int:question_id>/vote/", views.vote, name="vote"),
                ]

about/models.py
from django.db import models


# Create your models here.
class Bio(models.Model):
    biogoraphy = models.CharField(max_length=150)
    image = models.ImageField(upload_to="bios/", blank=True, null=True)

    def __str__(self):
        return self.biogoraphy


class Education(models.Model):
    college_name = models.CharField(max_length=100)
    degree = models.CharField(max_length=100)
    length_of_study = models.CharField(max_length=30)
    reflection = models.TextField()

    def __str__(self):
        return f"Majored in {self.degree} at {self.college_name} during {self.length_of_study}"


class Experience(models.Model):
    employer = models.CharField(max_length=100)
    job_title = models.CharField(max_length=100)
    location = models.CharField(max_length=100, blank=True)

    start_date = models.DateField()
    end_date = models.DateField(null=True, blank=True)

    responsibilities = models.TextField()

    def __str__(self):
        return (f""
                f"Employer:{self.employer}"
                f"\nTitle: {self.job_title}"
                f"\nLocation:{self.location}"
                f"\nDate Employed:{self.start_date} - {self.end_date}"
                )


class Skill(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return f"Skill: {self.name}"


class Hobby(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.name


class Interest(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.name

contact/models.py
from django.db import models

# Create your models here.

polls/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    
    ##string representation of the Question class objects
    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    ##string representation of the Choice class objects
    def __str__(self):
        return self.choice_text

about/forms.py
from django import forms
from .models import Hobby, Interest, Skill

class HobbyForm(forms.ModelForm):
    class Meta:
        model = Hobby
        fields = ['name','description']


class InterestForm(forms.ModelForm):
    class Meta:
        model = Interest
        fields = ['name', 'description']


class SkillForm(forms.ModelForm):
    class Meta:
        model = Skill
        fields = ['name']

contact/forms.py
#contact/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm',
        'placeholder':'Your Name'
        }))
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm',
        'placeholder': 'Your Email'
    }))
    message = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm',
        'placeholder': 'Your Message'
    }))




    

about/views.py
from django.contrib import messages
from django.shortcuts import render
from .models import Bio, Education, Experience, Skill, Hobby, Interest


def about(request):
    bio = Bio.objects.first()  # since there is only one bio instance FIXME I would grab by ID.
    education = Education.objects.all()
    experience = Experience.objects.all()
    skills = Skill.objects.all()
    hobbies = Hobby.objects.all()
    interests = Interest.objects.all()

    context = {
        'bio': bio,
        'education': education,
        'experience': experience,
        'skills': skills,
        'hobbies': hobbies,
        'interests': interests,
        'messages': messages.get_messages(request),
    }
    return render(request, 'about/index.html', context)

contact/views.py
from django.shortcuts import redirect, render
from django.contrib import messages
from django.core.mail import send_mail
from .forms import ContactForm

# Create your views here.

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            subject = f'Contact Form Submission from {name}'
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']
            full_message = f'Email: {email}\nMessage: {message}'

            send_mail(
                subject,
                full_message,
                email,
                ['jakedawg99@gmail.com'],
            )
            ##handle form submission
            messages.success(request, 'Thank you! Your message was sent and I will get back to you as soon as possible')
            return redirect('home')

    else:
        form = ContactForm()

    return render(request, 'contact/contact.html', {'form':form})
            

polls/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import Http404
from django.template import loader
from . models import Question


# Create your views here.

def index(request):
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    context = {"latest_question_list": latest_question_list,}
    return render(request, 'polls/index.html', context)
    
    return HttpResponse(template.render(context,request))



def detail(request, question_id):

   """
    try:
        question =
        Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, "polls/detail.html", {"question": question})
   """
   question = get_object_or_404(Question, pk=question_id)
   return render(request, 'polls/detail.html', {'question': question})
   


def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)


def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

about/templates/about/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MooreWeb</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>

<body class="bg-blue-100">

<!-- Top of Page Banner -->
<div class="bg-blue-300 text-white  flex items-center rounded-l-full">
    <div class="flex items-center">
        {% if bio.image %}
            <img src="{{ bio.image.url }}" alt="Profile Image" class="sm:w-36 sm:h-36 w-52 h-52 rounded-full  mr-6">
        {% endif %}
    </div>
	<div class="flex-col">
		<h1 class="pl-3 sm:text-3xl md:text-5xl lg:text-6xl font-bold">Welcome to Moore Web!</h1>
		<nav class="mt-5">
			<ul class="flex  pl-3 space-x-4">
				<li><a href="{% url 'home' %}" class="sm:text-1xl md:text-2xl lg:text-3xl text-blue-500 hover:text-blue-700">Home</a></li>
				<li><a href="{% url 'contact' %}" class="sm:text-1xl md:text-2xl lg:text-3xl text-blue-500 hover:text-blue-700">Contact</a></li>
			</ul>
		</nav>
	</div>
</div>

<!-- Social Media Icons -->
	<ul class="flex items-center space-x-4 ml-5 p-1">
	<!-- LinkedIn -->
		<li>
			<a href="http://linkedin.com/in/j-a-moore-dev" class="text-gray-600 hover:text-blue-500">
				<img src="{% static 'images/linkedin2.png' %}" alt="LinkedIn" class="h-8 w-8"/>   
			</a>
		</li>
	<!-- Github -->
		<li>
			<a href="https://github.com/Jacob-A-Moore" class="text-gray-600 hover:text-blue-500">
				<img src="{% static 'images/github3.png' %}" alt="Github" class="h-9 w-9"/>   
			</a>
		</li>
	<!-- Resume Download -->
		<li>
			<a href="{% static 'files/Resume_JMoore.pdf' %}" download>
				<img src="{% static 'images/resumeimg.png' %}" alt="Download Resume" class="h-9 w-9"/>
			</a>
		</li>
	</ul>
	
<!--  success message -->
	<div class="ml-5 p-1">
		{% if messages %}
			<div class="alert alert-success">
				{% for message in messages %}
					{{ message }}
				{% endfor %}
			</div>
		{% endif %}
	</div>
<!-- Bio Section -->
<section class="sm:p-0 p-4 bg-blue-200 flex flex-col"> 
        <h2 class="text-2xl lg:text-3xl text-blue-700 mt-5 ml-8">About Me</h2>
        <p class="indent-6 p-2"> 
            I am a driven technology professional with a deep passion for learning and continuously 
			expanding my skillset. Since 2021, I’ve immersed myself in popular programming languages like 
			C# and Python, alongside mastering frameworks such as .NET, ASP.NET, Django, and Tailwind CSS. 
			My journey into software engineering began with a lifelong love for video games, sparking my 
			curiosity in how technology works. Even though my focus is not video game development, this 
			passion fuels my commitment to staying current with new technologies and honing my craft to 
			build innovative solutions. 
        </p>
	<div class="flex ">
		{% load static %}
		<img src="{% static 'images/Circuit.png' %}" class="w-32 h-32 lg:w-34 lg:h-34 mr-2" alt="Binary Logic Illustration">
        <p class="indent-6">
            My introduction to working with computers began with my initial introduction to circuitry and binary logic through
			the Tennessee College of Applied Technology certification program in Industrial Electricity. 
			This program taught me the basics of circuitry, like Voltage, Resistance and Amperage as well
			as Impedence and Reactance. Upon mastering these basic concepts I was introduced to  control 
			logic wiring which exposed me to the concept of combinational logic. The intricacies of PLC's 
			and the circuitry involved in wiring input and outputs to perform specific tasks in a 
			particular order led me into doing research into Computer Science. 
        </p>
	</div>
	<div class="flex">
        <p class="indent-6 p-2 lg:p-4">
            Once I zeroed in on Software Development within the vast IT universe, I enrolled in Chattanooga State’s AAS
			program in Computer Programming, and my journey into the world of coding truly began. From my 
			first “Hello World!” in Java and C#, I was hooked. That curiosity soon evolved into building a 
			full-scale library management system with a team. My education not only sharpened my technical 
			abilities but also taught me how to thrive in team environments. Today, I continue honing my 
			skills, both in programming and in working as part of a team—because coding is rarely a solo 
			sport.
        </p>
		<img src="{%static 'images/studymanCS2.png' %}" class="w-32 h-32 md:w-34 md:h-34 p-4 lg:p-2 lg:w-36 lg:h-36" alt="study man">
	</div>
    
</section>



    <!-- Education Section -->
    <section class="p-4">
		{% load static %}
        <h2 class="flex items-center text-2xl text-blue-700">
		Education
		<img src="{% static 'images/gradcap2.png' %}" alt="edu-icon" class=" ml-2 h-8 w-8">
		</h2>
        <ul>
            {% for edu in education %}
                <li><span class="text-blue-500"> College: </span> {{ edu.college_name }}</li>
				<li><span class="text-blue-500"> Degree: </span>{{ edu.degree }}</li>
				<li><span class="text-blue-500"> Duration: </span> {{ edu.length_of_study }}</li>
				<li><span class="text-blue-500"> Reflection: </span> {{ edu.reflection }} </li>
            {% empty %}
                <li>No education records found.</li>
            {% endfor %}
        </ul>
    </section>

    <!-- Experience Section -->
    <section class="bg-blue-200 p-4">
		{% load static %}
        <h2 class="flex items-center text-2xl text-blue-700">
		Experience
		<img src="{% static 'images/workxp.png' %}" alt="xp-icon" class=" ml-2 h-6 w-6">
		</h2>
        <ul>
            {% for exp in experience %}
                <li><span class="text-blue-500"> Employer: </span> {{ exp.employer }}</li>
				<li><span class="text-blue-500"> Location: </span> {{ exp.location}}</li>
				<li><span class="text-blue-500"> Title: </span> {{ exp.job_title}}</li>
				<li><span class="text-blue-500"> Duration: </span> {{ exp.start_date}} - {{exp.end_date}}</li>
				<li><span class="text-blue-500"> Responsibilities: </span> {{ exp.responsibilities}}</li>
				
            {% empty %}
                <li>No experience records found.</li>
            {% endfor %}
        </ul>
    </section>

    <!-- Skills Section -->
    <section class="p-4">
	    {% load static %}
        <h2 class="flex items-center text-2xl text-blue-700">
		Skills
		<img src="{% static 'images/skills2.png' %}" alt="skills-icon" class="ml-2 h-6 w-6">
		</h2>
		<div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 overflow-y-auto max-h-64">
			{% for skill in skills %}
				<div class="bg-blue-300 p-2 rounded">
					{{skill.name}}
				</div>
				
			{% empty %}
				<div> No skills listed. </div>
			{% endfor %}
			<p> And Still Growing...</p>
        </div>
    </section>

    <!-- Hobbies Section -->
    <section class="p-4">
        <h2 class="text-2xl text-blue-700">Hobbies</h2>
        <ul>
            {% for hobby in hobbies %}
                <li>{{ hobby }}</li>
            {% empty %}
                <li>No hobbies listed.</li>
            {% endfor %}
        </ul>
    </section>

    <!-- Interests Section -->
    <section class="p-4">
        <h2 class="text-2xl text-blue-700">Interests</h2>
        <ul>
            {% for interest in interests %}
                <li>{{ interest }}</li>
            {% empty %}
                <li>No interests listed.</li>
            {% endfor %}
        </ul>
    </section>
</body>
</html>

about/templates/about/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test Tailwind</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body class="bg-blue-100">
    <h1 class="bg-blue-300 text-white p-4">Hello, Tailwind!</h1>
</body>
</html>

contact/templates/contact/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial scale=1.0">
    <title>Contact Me</title>
	{% load static %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body class=" flex items-center justify-center min-h-screen bg-blue-300">

	<div class="bg-white shadow-lg rounded p-8">
		<div class="flex flex-row">
			<h1 class="text-3xl mb-4 text-blue-500">Contact Me</h1>
			<img src="{% static 'images/email.png'%}" alt="Email Icon" class="mb-4 ml-auto w-16 h-16">
		</div>
		<form method="post">
			{% csrf_token %}
			<div class="mb-4">
			{{ form.name }}
			</div>
			<div class="mb-4">
			{{ form.email }}
			</div>
			<div class="mb-4">
			{{ form.message }}
			</div>
			<!-- Send button and Thanks message -->
			<div class="flex items-center justify-between">
			<button type="submit" class="px-4 py-2 bg-blue-500 text-white rounded-md">Send</button>
			<span class="text-blue-500 ml-4"> Thanks for reaching out!</span>
			</div>
		</form>
	</div>
</body>
</html>

contact/templates/contact/thanks.html
<!DOCTYPE html>
<html>
<head>
    <title>Thank You</title>
</head>
<body>
	<h1>Thank you for your message!</h1>
	<p>I will get back to you soon, your message is of great value to me.</p>
</body>
</html>

polls/templates/polls/detail.html
<h1>{{question.question_text}}</h1>
<ul>
{% for choice in question.choice_set.all %}
	<li>{{ choice.choice_text }}</li>
{% endfor%}
</ul>

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{%url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
   